### ISSUE TITLE
Boxart XL

### ISSUE THREAD

**Issue by chronoss09** [KirovAir/TwilightBoxart#5]
Hi !

I like this one but some covers don't show on Twilight, if u can do something, it will be great but other work well.

Thanks a lot !!!

**Comment by KirovAir** [comment]
Try to disable boxart cache in TWL++ settings on your console.

**Comment by karasuhebi** [comment]
Can this be added somewhere so people know it's a known issue?
Maybe add it to https://wiki.ds-homebrew.com/twilightmenu/how-to-get-box-art?

**Comment by karasuhebi** [comment]
Can this be added somewhere so people know it's a known issue?
Maybe add it to https://wiki.ds-homebrew.com/twilightmenu/how-to-get-box-art?

BTW I figured out what the issue is. It's file size. I guess TWiLight Menu++ has a limit on what it can cache.

Confirmed with Rocket Robz that the file size limit is 44 KB.
